list: $/pensoft/projectinitiatives/models/funding/columns.yaml
modelClass: Pensoft\Projectinitiatives\Models\Funding
title: Fundings
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'pensoft/projectinitiatives/fundings/update/:id'
