list: $/pensoft/projectinitiatives/models/landscape/columns.yaml
modelClass: Pensoft\Projectinitiatives\Models\Landscape
title: Landscapes
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'pensoft/projectinitiatives/landscapes/update/:id'
