list: $/pensoft/projectinitiatives/models/region/columns.yaml
modelClass: Pensoft\Projectinitiatives\Models\Region
title: Regions
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'pensoft/projectinitiatives/regions/update/:id'
