list: $/pensoft/projectinitiatives/models/approach/columns.yaml
modelClass: Pensoft\Projectinitiatives\Models\Approach
title: Approaches
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'pensoft/projectinitiatives/approaches/update/:id'